@host = http://localhost:5252

GET {{host}}/api/storage
Accept: application/json

###

POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin@123"
}

###
